### PR TITLE
use .local instead of .dev

### LINKED ISSUE #4: Use .local instead of .dev
.dev is an official TLD since summer 2014 an causes some DNS problems, especially under windows-systems. Better use .local als domain.

### PR DESCRIPTION
**Pull request by alfredbez**
closes #4

### CODE REVIEW

**Comment by rezonanc-oxid** [comment]
Unfortunately we can't accept this even as a compromise solution. There will be few problems/side-effects because of this change:

1) `config.inc.php` is only able to handle one single host name/entry;
2) Apache virtual host configuration contains only single `ServerName` entry;
3) A side-effect is created, i.e. if you would visit `www.oxideshop.dev` all the links will point to `www.oxideshop.local`;

Unfortunately this solution would only lead to more possible problems and confusion. I really would suggest to use the `personal.yml` file as a way to change the host name if it really causes trouble on your system.

Would you agree that we could close this?

**Comment by alfredbez** [comment]
https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

**Comment by Sieg** [comment]
Hello @alfredbez, is this one still viable?

**Comment by rezonanc-oxid** [comment]
I've already brought this PR to https://github.com/OXID-eSales/oxvm_base/commit/54c944883df7db5e00b989c4dd148e1546125f16 and these changes are already present in this repository by @PirxDanford via https://github.com/OXID-eSales/oxvm_eshop/commit/8cd62496737dd9cda110ff908907ea048b8fce65 .

I would suggest to close this.

**Comment by Sieg** [comment]
Yah, thank you for clarifying @rezonanc-oxid, closing the PR. Have a nice day!

**Pull request closed without merging**
